apiVersion: v2.edp.epam.com/v1alpha1
kind: Codebase
metadata:
  name: java-maven-create
spec:
  buildTool: Maven
  ciTool: Jenkins
  defaultBranch: master
  deploymentScript: helm-chart
  framework: java11
  gitServer: gerrit
  jenkinsSlave: maven-java11
  jobProvisioning: default
  lang: Java
  route:
    path: /
    site: route
  strategy: create
  type: application
  versioning:
    type: default
